# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /var/lib/snapd/snap/clion/152/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /var/lib/snapd/snap/clion/152/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tony/Documents/Dungeon/Code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tony/Documents/Dungeon/Code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/var/lib/snapd/snap/clion/152/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/var/lib/snapd/snap/clion/152/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tony/Documents/Dungeon/Code/CMakeFiles /home/tony/Documents/Dungeon/Code//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tony/Documents/Dungeon/Code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Dungeon

# Build rule for target.
Dungeon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Dungeon
.PHONY : Dungeon

# fast build rule for target.
Dungeon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/build
.PHONY : Dungeon/fast

Color.o: Color.cpp.o

.PHONY : Color.o

# target to build an object file
Color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Color.cpp.o
.PHONY : Color.cpp.o

Color.i: Color.cpp.i

.PHONY : Color.i

# target to preprocess a source file
Color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Color.cpp.i
.PHONY : Color.cpp.i

Color.s: Color.cpp.s

.PHONY : Color.s

# target to generate assembly for a file
Color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Color.cpp.s
.PHONY : Color.cpp.s

Dungeon.o: Dungeon.cpp.o

.PHONY : Dungeon.o

# target to build an object file
Dungeon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Dungeon.cpp.o
.PHONY : Dungeon.cpp.o

Dungeon.i: Dungeon.cpp.i

.PHONY : Dungeon.i

# target to preprocess a source file
Dungeon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Dungeon.cpp.i
.PHONY : Dungeon.cpp.i

Dungeon.s: Dungeon.cpp.s

.PHONY : Dungeon.s

# target to generate assembly for a file
Dungeon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Dungeon.cpp.s
.PHONY : Dungeon.cpp.s

FireMonster.o: FireMonster.cpp.o

.PHONY : FireMonster.o

# target to build an object file
FireMonster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/FireMonster.cpp.o
.PHONY : FireMonster.cpp.o

FireMonster.i: FireMonster.cpp.i

.PHONY : FireMonster.i

# target to preprocess a source file
FireMonster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/FireMonster.cpp.i
.PHONY : FireMonster.cpp.i

FireMonster.s: FireMonster.cpp.s

.PHONY : FireMonster.s

# target to generate assembly for a file
FireMonster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/FireMonster.cpp.s
.PHONY : FireMonster.cpp.s

GameCharacter.o: GameCharacter.cpp.o

.PHONY : GameCharacter.o

# target to build an object file
GameCharacter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/GameCharacter.cpp.o
.PHONY : GameCharacter.cpp.o

GameCharacter.i: GameCharacter.cpp.i

.PHONY : GameCharacter.i

# target to preprocess a source file
GameCharacter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/GameCharacter.cpp.i
.PHONY : GameCharacter.cpp.i

GameCharacter.s: GameCharacter.cpp.s

.PHONY : GameCharacter.s

# target to generate assembly for a file
GameCharacter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/GameCharacter.cpp.s
.PHONY : GameCharacter.cpp.s

IceMonster.o: IceMonster.cpp.o

.PHONY : IceMonster.o

# target to build an object file
IceMonster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/IceMonster.cpp.o
.PHONY : IceMonster.cpp.o

IceMonster.i: IceMonster.cpp.i

.PHONY : IceMonster.i

# target to preprocess a source file
IceMonster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/IceMonster.cpp.i
.PHONY : IceMonster.cpp.i

IceMonster.s: IceMonster.cpp.s

.PHONY : IceMonster.s

# target to generate assembly for a file
IceMonster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/IceMonster.cpp.s
.PHONY : IceMonster.cpp.s

Item.o: Item.cpp.o

.PHONY : Item.o

# target to build an object file
Item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Item.cpp.o
.PHONY : Item.cpp.o

Item.i: Item.cpp.i

.PHONY : Item.i

# target to preprocess a source file
Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Item.cpp.i
.PHONY : Item.cpp.i

Item.s: Item.cpp.s

.PHONY : Item.s

# target to generate assembly for a file
Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Item.cpp.s
.PHONY : Item.cpp.s

Monster.o: Monster.cpp.o

.PHONY : Monster.o

# target to build an object file
Monster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Monster.cpp.o
.PHONY : Monster.cpp.o

Monster.i: Monster.cpp.i

.PHONY : Monster.i

# target to preprocess a source file
Monster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Monster.cpp.i
.PHONY : Monster.cpp.i

Monster.s: Monster.cpp.s

.PHONY : Monster.s

# target to generate assembly for a file
Monster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Monster.cpp.s
.PHONY : Monster.cpp.s

NPC.o: NPC.cpp.o

.PHONY : NPC.o

# target to build an object file
NPC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/NPC.cpp.o
.PHONY : NPC.cpp.o

NPC.i: NPC.cpp.i

.PHONY : NPC.i

# target to preprocess a source file
NPC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/NPC.cpp.i
.PHONY : NPC.cpp.i

NPC.s: NPC.cpp.s

.PHONY : NPC.s

# target to generate assembly for a file
NPC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/NPC.cpp.s
.PHONY : NPC.cpp.s

Object.o: Object.cpp.o

.PHONY : Object.o

# target to build an object file
Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Object.cpp.o
.PHONY : Object.cpp.o

Object.i: Object.cpp.i

.PHONY : Object.i

# target to preprocess a source file
Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Object.cpp.i
.PHONY : Object.cpp.i

Object.s: Object.cpp.s

.PHONY : Object.s

# target to generate assembly for a file
Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Object.cpp.s
.PHONY : Object.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Player.cpp.s
.PHONY : Player.cpp.s

Record.o: Record.cpp.o

.PHONY : Record.o

# target to build an object file
Record.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Record.cpp.o
.PHONY : Record.cpp.o

Record.i: Record.cpp.i

.PHONY : Record.i

# target to preprocess a source file
Record.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Record.cpp.i
.PHONY : Record.cpp.i

Record.s: Record.cpp.s

.PHONY : Record.s

# target to generate assembly for a file
Record.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Record.cpp.s
.PHONY : Record.cpp.s

Room.o: Room.cpp.o

.PHONY : Room.o

# target to build an object file
Room.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Room.cpp.o
.PHONY : Room.cpp.o

Room.i: Room.cpp.i

.PHONY : Room.i

# target to preprocess a source file
Room.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Room.cpp.i
.PHONY : Room.cpp.i

Room.s: Room.cpp.s

.PHONY : Room.s

# target to generate assembly for a file
Room.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/Room.cpp.s
.PHONY : Room.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/main.cpp.s
.PHONY : main.cpp.s

moon.o: moon.cpp.o

.PHONY : moon.o

# target to build an object file
moon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/moon.cpp.o
.PHONY : moon.cpp.o

moon.i: moon.cpp.i

.PHONY : moon.i

# target to preprocess a source file
moon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/moon.cpp.i
.PHONY : moon.cpp.i

moon.s: moon.cpp.s

.PHONY : moon.s

# target to generate assembly for a file
moon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dungeon.dir/build.make CMakeFiles/Dungeon.dir/moon.cpp.s
.PHONY : moon.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Dungeon"
	@echo "... Color.o"
	@echo "... Color.i"
	@echo "... Color.s"
	@echo "... Dungeon.o"
	@echo "... Dungeon.i"
	@echo "... Dungeon.s"
	@echo "... FireMonster.o"
	@echo "... FireMonster.i"
	@echo "... FireMonster.s"
	@echo "... GameCharacter.o"
	@echo "... GameCharacter.i"
	@echo "... GameCharacter.s"
	@echo "... IceMonster.o"
	@echo "... IceMonster.i"
	@echo "... IceMonster.s"
	@echo "... Item.o"
	@echo "... Item.i"
	@echo "... Item.s"
	@echo "... Monster.o"
	@echo "... Monster.i"
	@echo "... Monster.s"
	@echo "... NPC.o"
	@echo "... NPC.i"
	@echo "... NPC.s"
	@echo "... Object.o"
	@echo "... Object.i"
	@echo "... Object.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Record.o"
	@echo "... Record.i"
	@echo "... Record.s"
	@echo "... Room.o"
	@echo "... Room.i"
	@echo "... Room.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... moon.o"
	@echo "... moon.i"
	@echo "... moon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

